stages:
  - build
  - test
  - deploy

default:
  image: node:latest

build-backend:
  stage: build
  script:
    - echo 'backend build'
    - cd back
    - npm i


test-backend:
  stage: test
  script:
    - echo 'backend test'
    - cd back
    - npm run test

deploy-backend:
  stage: deploy
  script:
    - echo 'deploy build'
