stages:
  - build
  - test
  - deploy

default:
  image: node:latest

build-backend:
  stage: build
  script:
    - echo 'backend build'

test-backend:
  stage: test
  script:
    - echo 'backend test'

deploy-backend:
  stage: deploy
  script:
    - echo 'deploy build'
